# .github/workflows/snake.yml
name: Generate Snake Animation

permissions:
  contents: write  # Dá permissão para fazer commit/push

on:
  schedule:
    - cron: "0 0 * * *"  # executa diariamente às 00:00 UTC
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: PamelaXisto
          outputs: |
            ./output/github-snake.svg
            ./output/github-snake-dark.svg

      - name: Commit files
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A
          git commit -m "Generate snake animation"
          git push

